name: Deploy Next.js to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: www.duarizwan.com
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Build and export Next.js site
        run: |
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create S3 bucket if not exists
        run: |
          aws s3api create-bucket --bucket $BUCKET_NAME --region $AWS_REGION || true
          aws s3api put-public-access-block \
            --bucket $BUCKET_NAME \
            --public-access-block-configuration \
              BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false

      - name: Configure static website hosting
        run: |
          aws s3 website s3://$BUCKET_NAME/ \
            --index-document index.html \
            --error-document 404.html

      - name: Apply bucket policy
        run: |
          cat > policy.json <<EOF
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "PublicReadGetObject",
                "Effect": "Allow",
                "Principal": "*",
                "Action": ["s3:GetObject"],
                "Resource": ["arn:aws:s3:::$BUCKET_NAME/*"]
              }
            ]
          }
          EOF
          aws s3api put-bucket-policy --bucket $BUCKET_NAME --policy file://policy.json

      - name: Sync out/ to S3
        run: aws s3 sync out/ s3://$BUCKET_NAME/ --delete
